apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
   name: backstage
   labels:
    environment: backstage
spec:
   stateStoreRef:
      name: default
      kind: GitStateStore