---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-credentials
  namespace: flux-system
type: Opaque
data:
  username: dmlzYWxpc2hhbGluaQ==
  password: Z2xwYXQtd2Y0OHoyUFhHS3lnQmdGSGRnZVk=
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kratix-bucket
  namespace: flux-system
spec:
  interval: 10s
  url: https://gitlab.com/visalishalini/testtfe
  ref:  
    branch: main
  secretRef:
    name: gitlab-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kratix-workload-dependencies
  namespace: flux-system
spec:
  interval: 8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: kratix-bucket
  path: ./EC2/worker-cluster/dependencies
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kratix-workload-resources
  namespace: flux-system
spec:
  interval: 3s
  prune: true
  dependsOn:
  - name: kratix-workload-dependencies
  sourceRef:
    kind: GitRepository
    name: kratix-bucket
  path: ./EC2/worker-cluster/resources